%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%   Consensus Protocol class takes care of consensus algorithm based on
%   1) Distributed Kalman Filtering.
%   2) ADMM based consensus for semantic fusion.
%
%   Author -- Santhoshkumar Sunderrajan( santhosh@ece.ucsb.edu )
%   Website -- http://vision.ece.ucsb.edu/~santhosh/ 
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
classdef ConsensusProtocol < handle

    methods(Static)
        
        % Performs consensus based on the options specified
        cameraNetwork = PerformConsensus(  cameraNetwork,...
                                           useADMMBasedConsensus,...
                                           usePrinicipalAxis,...
                                           maximumNumberOfConsensusIterations,...
                                           shouldUseDynamicContext,...
                                           shouldUseStaticContext,...
                                           shouldUseSpatialContext  );
                                       
    end%static methods
    
    % Constant member variables
    properties(Constant)
        ALPHA 	 = Config.ALPHA;
        BETA     = Config.BETA;
        GAMMA    = Config.GAMMA;
        LAMBDA   = Config.LAMBDA;
        RHO      = Config.RHO;
    end
    
    methods( Static, Access = private )        
        % ADMM based consensus
        cameraNetwork = PerformADMMBasedConsensus(  cameraNetwork,...
                                                    shouldUsePrincipalAxisToFindTheGroundPlaneLocation,...
                                                    maximumNumberOfConsensusIterations,...
                                                    shouldUseDynamicContext,...
                                                    shouldUseStaticContext,...
                                                    shouldUseSpatialContext );
                  
        % ADMM based consensus with semantic knowledge
        x = PerformConsensusByADMMWithoutSemanticKnowledge(  neighborMeasurements,...
                                                             measurementWeights,...
                                                             lambda  );
        
        % ADMM based consensus without semantic knowledge
        x = PerformConsensusByADMMWithSemanticKnowledge(   neighborMeasurements,...
                                                           measurementWeights,...
                                                           lambda,...
                                                           dynamicPositionInformation,...
                                                           staticExitSceneInformation,...
                                                           dij,...
                                                           zj )
                                                       
       % Collect Measurements from other cameras for the corresponding target                   
       [ zi, wi, yi, si, xPriors ] = CollectMeasurments( cameraNetwork,...
                                                         cameraIndex,...
                                                         targetIndex );
                                                 
       % Collects spatial context information for contextual fusion
       [ dij, zj ]                 = CollectContextInformation( cameraNetwork,...
                                                                cameraIndex,...
                                                                targetIndex );
    end
   
end%classdef